source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CQPopUpMenu_Example', :exclusive => true do
  pod 'CQPopUpMenu', :path => '../'
end

target 'CQPopUpMenu_Tests', :exclusive => true do
  pod 'CQPopUpMenu', :path => '../'

  
end
